@@ .. @@
         business_id,
         title,
         description,
+        image_url,
         original_price,
@@ .. @@
         business_1_id,
         'Coupe + Brushing + Soin Professionnel',
         'Service complet incluant coupe moderne, brushing professionnel et soin capillaire nourrissant. Nos stylistes expérimentés vous conseillent pour sublimer votre look selon votre morphologie et style de vie.',
+        'https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=800',
         450,
@@ .. @@
         business_1_id,
         'Coloration Complète + Coupe + Brushing',
         'Transformation capillaire complète avec coloration professionnelle, coupe personnalisée et brushing. Produits haut de gamme et techniques avancées pour un résultat exceptionnel.',
+        'https://images.pexels.com/photos/3993456/pexels-photo-3993456.jpeg?auto=compress&cs=tinysrgb&w=800',
         800,
@@ .. @@
         business_2_id,
         'Massage Relaxant aux Huiles Essentielles',
         'Massage complet du corps de 60 minutes aux huiles essentielles d''argan et de lavande. Technique de relaxation profonde pour évacuer le stress et les tensions.',
+        'https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg?auto=compress&cs=tinysrgb&w=800',
         400,
@@ .. @@
         business_2_id,
         'Hammam Traditionnel + Gommage + Enveloppement',
         'Expérience hammam authentique avec gommage au savon noir, enveloppement à l''argile et relaxation. Rituel complet de purification et détente.',
+        'https://images.pexels.com/photos/6663589/pexels-photo-6663589.jpeg?auto=compress&cs=tinysrgb&w=800',
         350,
@@ .. @@
         business_3_id,
         'Manucure Complète + Vernis Semi-Permanent',
         'Manucure professionnelle avec soin des cuticules, limage, polissage et pose de vernis semi-permanent longue tenue. Plus de 50 couleurs disponibles.',
+        'https://images.pexels.com/photos/3997993/pexels-photo-3997993.jpeg?auto=compress&cs=tinysrgb&w=800',
         200,
@@ .. @@
         business_3_id,
         'Nail Art Créatif + Manucure',
         'Création artistique personnalisée sur ongles avec motifs uniques, strass, paillettes. Service premium pour occasions spéciales.',
+        'https://images.pexels.com/photos/3997992/pexels-photo-3997992.jpeg?auto=compress&cs=tinysrgb&w=800',
         350,
@@ .. @@
         business_4_id,
         'Soin Visage Anti-Âge Premium',
         'Soin complet anti-âge avec nettoyage profond, peeling enzymatique, masque collagène et sérum hydratant. Technologie LED incluse.',
+        'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=800',
         600,
@@ .. @@
         business_4_id,
         'Épilation Laser - Zone au Choix',
         'Séance d''épilation laser définitive sur zone au choix (jambes, aisselles, maillot). Technologie laser dernière génération, résultats durables.',
+        'https://images.pexels.com/photos/4041394/pexels-photo-4041394.jpeg?auto=compress&cs=tinysrgb&w=800',
         300,
@@ .. @@
         business_5_id,
         'Maquillage Soirée Professionnel',
         'Maquillage professionnel pour soirée avec produits haut de gamme et techniques avancées. Look personnalisé selon votre style et événement.',
+        'https://images.pexels.com/photos/4041397/pexels-photo-4041397.jpeg?auto=compress&cs=tinysrgb&w=800',
         300,