/*
  # Fix QR Code Duplication - Keep Working Trigger

  1. Changes Made
    - Remove QR code generation from confirm_booking_and_generate_qr function
    - Keep the working database trigger that generates QR codes correctly
    - Clean up any existing duplicate QR codes
    - Update confirmation function to only handle booking status updates

  2. Security
    - Maintain existing RLS policies
    - Keep all validation logic intact

  3. Notes
    - The database trigger `trigger_generate_qr_code` will remain as the single source of QR generation
    - QR codes will be generated automatically when bookings are inserted
    - No manual QR generation in application code
*/

-- First, clean up any duplicate QR codes (keep the most recent one per booking)
DELETE FROM qr_codes 
WHERE id NOT IN (
  SELECT DISTINCT ON (booking_id) id 
  FROM qr_codes 
  ORDER BY booking_id, created_at DESC
);

-- Update the confirm_booking_and_generate_qr function to NOT generate QR codes
-- since the trigger already handles this correctly
CREATE OR REPLACE FUNCTION confirm_booking_and_generate_qr(
  p_booking_id UUID,
  p_confirmed_datetime TIMESTAMPTZ
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_booking bookings%ROWTYPE;
  v_deal deals%ROWTYPE;
  v_business businesses%ROWTYPE;
  v_qr_code qr_codes%ROWTYPE;
  v_commission_amount NUMERIC(10,2);
  v_salon_amount NUMERIC(10,2);
  v_result JSON;
BEGIN
  -- Get booking details
  SELECT * INTO v_booking
  FROM bookings
  WHERE id = p_booking_id;

  IF NOT FOUND THEN
    RETURN json_build_object(
      'success', false,
      'error', 'Booking not found'
    );
  END IF;

  -- Check if booking is in pending status
  IF v_booking.status != 'pending' THEN
    RETURN json_build_object(
      'success', false,
      'error', 'Booking is not in pending status'
    );
  END IF;

  -- Get deal and business details
  SELECT * INTO v_deal FROM deals WHERE id = v_booking.deal_id;
  SELECT * INTO v_business FROM businesses WHERE id = v_deal.business_id;

  -- Update booking status to confirmed
  UPDATE bookings 
  SET 
    status = 'confirmed',
    booking_date = p_confirmed_datetime,
    updated_at = NOW()
  WHERE id = p_booking_id;

  -- Calculate commission (15% default)
  v_commission_amount := v_booking.total_price * COALESCE(v_business.commission_rate, 0.15);
  v_salon_amount := v_booking.total_price - v_commission_amount;

  -- Get the QR code that was automatically generated by the trigger
  SELECT * INTO v_qr_code
  FROM qr_codes
  WHERE booking_id = p_booking_id
  ORDER BY created_at DESC
  LIMIT 1;

  -- If no QR code exists (shouldn't happen with trigger), return error
  IF NOT FOUND THEN
    RETURN json_build_object(
      'success', false,
      'error', 'QR code not found - trigger may have failed'
    );
  END IF;

  -- Create commission log
  INSERT INTO commission_logs (
    booking_id,
    business_id,
    commission_rate,
    deal_amount,
    commission_amount,
    salon_amount,
    status,
    validated_at
  ) VALUES (
    p_booking_id,
    v_business.id,
    COALESCE(v_business.commission_rate, 0.15),
    v_booking.total_price,
    v_commission_amount,
    v_salon_amount,
    'pending',
    NULL
  );

  -- Return success with details
  RETURN json_build_object(
    'success', true,
    'booking_id', p_booking_id,
    'qr_token', v_qr_code.qr_token,
    'customer_name', v_booking.customer_name,
    'service_name', v_deal.title,
    'business_name', v_business.name,
    'booking_date', p_confirmed_datetime,
    'commission_amount', v_commission_amount,
    'salon_amount', v_salon_amount
  );
END;
$$;

-- Ensure the trigger function exists and works correctly
-- (This should already exist, but let's make sure it's properly defined)
CREATE OR REPLACE FUNCTION generate_qr_code_for_booking()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_qr_token TEXT;
  v_expires_at TIMESTAMPTZ;
BEGIN
  -- Generate unique QR token with booking ID and timestamp
  v_qr_token := 'QR_' || NEW.id || '_' || EXTRACT(EPOCH FROM NOW())::BIGINT;
  
  -- Set expiration to 30 days from now
  v_expires_at := NOW() + INTERVAL '30 days';
  
  -- Insert QR code
  INSERT INTO qr_codes (
    booking_id,
    qr_token,
    is_used,
    expires_at
  ) VALUES (
    NEW.id,
    v_qr_token,
    false,
    v_expires_at
  );
  
  -- Update the booking with the QR code ID
  UPDATE bookings 
  SET qr_code_id = (
    SELECT id FROM qr_codes 
    WHERE booking_id = NEW.id 
    ORDER BY created_at DESC 
    LIMIT 1
  )
  WHERE id = NEW.id;
  
  RETURN NEW;
END;
$$;

-- Ensure the trigger exists and is properly attached
DROP TRIGGER IF EXISTS trigger_generate_qr_code ON bookings;
CREATE TRIGGER trigger_generate_qr_code
  AFTER INSERT ON bookings
  FOR EACH ROW
  EXECUTE FUNCTION generate_qr_code_for_booking();

-- Verify no orphaned QR codes exist
DELETE FROM qr_codes 
WHERE booking_id NOT IN (SELECT id FROM bookings);