/*
  # Fix Duplicate QR Code Generation

  1. Problem Analysis
    - Two QR codes are being generated for each booking
    - First QR code: Generated by trigger on booking INSERT (wrong format)
    - Second QR code: Generated by confirm_booking_and_generate_qr function (correct format)
    - Only the second one works because it has the correct token format

  2. Solution
    - Drop the problematic trigger that creates QR codes on booking INSERT
    - Drop the associated function that generates incorrect QR codes
    - Clean up existing duplicate QR codes
    - Ensure only confirm_booking_and_generate_qr creates QR codes

  3. Changes
    - Remove trigger_generate_qr_code trigger
    - Remove generate_qr_code_for_booking() function
    - Clean up duplicate QR codes in database
    - Update bookings table to reference correct QR codes only
*/

-- Step 1: Drop the problematic trigger that creates QR codes on booking INSERT
DROP TRIGGER IF EXISTS trigger_generate_qr_code ON bookings;

-- Step 2: Drop the function that generates incorrect QR codes
DROP FUNCTION IF EXISTS generate_qr_code_for_booking();

-- Step 3: Clean up duplicate QR codes - keep only the most recent one per booking
WITH ranked_qr_codes AS (
  SELECT 
    id,
    booking_id,
    qr_token,
    created_at,
    ROW_NUMBER() OVER (PARTITION BY booking_id ORDER BY created_at DESC) as rn
  FROM qr_codes
),
qr_codes_to_delete AS (
  SELECT id 
  FROM ranked_qr_codes 
  WHERE rn > 1
)
DELETE FROM qr_codes 
WHERE id IN (SELECT id FROM qr_codes_to_delete);

-- Step 4: Update bookings table to reference the correct (remaining) QR codes
UPDATE bookings 
SET qr_code_id = (
  SELECT qr.id 
  FROM qr_codes qr 
  WHERE qr.booking_id = bookings.id 
  LIMIT 1
)
WHERE qr_code_id IS NULL OR qr_code_id NOT IN (
  SELECT id FROM qr_codes WHERE booking_id = bookings.id
);

-- Step 5: Ensure the confirm_booking_and_generate_qr function is the ONLY way to create QR codes
-- Update the function to check for existing QR codes and not create duplicates
CREATE OR REPLACE FUNCTION confirm_booking_and_generate_qr(
  p_booking_id UUID,
  p_confirmed_datetime TIMESTAMPTZ DEFAULT NOW()
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_booking bookings%ROWTYPE;
  v_deal deals%ROWTYPE;
  v_business businesses%ROWTYPE;
  v_qr_token TEXT;
  v_qr_id UUID;
  v_commission_amount NUMERIC(10,2);
  v_salon_amount NUMERIC(10,2);
  v_expires_at TIMESTAMPTZ;
  v_result JSON;
BEGIN
  -- Get booking details
  SELECT * INTO v_booking FROM bookings WHERE id = p_booking_id;
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Booking not found');
  END IF;

  -- Get deal details
  SELECT * INTO v_deal FROM deals WHERE id = v_booking.deal_id;
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Deal not found');
  END IF;

  -- Get business details
  SELECT * INTO v_business FROM businesses WHERE id = v_deal.business_id;
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Business not found');
  END IF;

  -- Check if QR code already exists for this booking
  IF EXISTS (SELECT 1 FROM qr_codes WHERE booking_id = p_booking_id) THEN
    RETURN json_build_object('success', false, 'error', 'QR code already exists for this booking');
  END IF;

  -- Generate QR token with consistent format: QR_<booking_id>_<timestamp>
  v_qr_token := 'QR_' || p_booking_id::TEXT || '_' || EXTRACT(EPOCH FROM p_confirmed_datetime)::BIGINT::TEXT;
  
  -- Set expiration (24 hours from confirmation)
  v_expires_at := p_confirmed_datetime + INTERVAL '24 hours';

  -- Insert QR code
  INSERT INTO qr_codes (booking_id, qr_token, expires_at, is_used)
  VALUES (p_booking_id, v_qr_token, v_expires_at, false)
  RETURNING id INTO v_qr_id;

  -- Update booking status and link to QR code
  UPDATE bookings 
  SET 
    status = 'confirmed',
    qr_code_id = v_qr_id,
    validated_at = NULL,
    updated_at = NOW()
  WHERE id = p_booking_id;

  -- Calculate commission
  v_commission_amount := v_deal.discounted_price * v_business.commission_rate;
  v_salon_amount := v_deal.discounted_price - v_commission_amount;

  -- Create commission log
  INSERT INTO commission_logs (
    booking_id, business_id, commission_rate, deal_amount, 
    commission_amount, salon_amount, status
  ) VALUES (
    p_booking_id, v_business.id, v_business.commission_rate, 
    v_deal.discounted_price, v_commission_amount, v_salon_amount, 'pending'
  );

  -- Return success result
  v_result := json_build_object(
    'success', true,
    'booking_id', p_booking_id,
    'qr_token', v_qr_token,
    'qr_id', v_qr_id,
    'customer_name', v_booking.customer_name,
    'service_name', v_deal.title,
    'business_name', v_business.name,
    'deal_amount', v_deal.discounted_price,
    'commission_amount', v_commission_amount,
    'salon_amount', v_salon_amount,
    'commission_rate', v_business.commission_rate,
    'expires_at', v_expires_at
  );

  RETURN v_result;
END;
$$;

-- Step 6: Update the validation function to handle the correct token format
CREATE OR REPLACE FUNCTION validate_booking_with_qr(
  p_qr_token TEXT,
  p_business_id UUID,
  p_staff_id UUID
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_qr_code qr_codes%ROWTYPE;
  v_booking bookings%ROWTYPE;
  v_deal deals%ROWTYPE;
  v_business businesses%ROWTYPE;
  v_commission_amount NUMERIC(10,2);
  v_salon_amount NUMERIC(10,2);
  v_loyalty_points INTEGER := 10;
  v_result JSON;
BEGIN
  -- Find QR code by token
  SELECT * INTO v_qr_code FROM qr_codes WHERE qr_token = p_qr_token;
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Code QR invalide ou expiré');
  END IF;

  -- Check if QR code is expired
  IF v_qr_code.expires_at < NOW() THEN
    RETURN json_build_object('success', false, 'error', 'Code QR expiré');
  END IF;

  -- Check if QR code is already used
  IF v_qr_code.is_used THEN
    RETURN json_build_object('success', false, 'error', 'Code QR déjà utilisé');
  END IF;

  -- Get booking details
  SELECT * INTO v_booking FROM bookings WHERE id = v_qr_code.booking_id;
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Réservation non trouvée');
  END IF;

  -- Get deal details
  SELECT * INTO v_deal FROM deals WHERE id = v_booking.deal_id;
  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Offre non trouvée');
  END IF;

  -- Get business details and verify ownership
  SELECT * INTO v_business FROM businesses WHERE id = v_deal.business_id;
  IF NOT FOUND OR v_business.id != p_business_id THEN
    RETURN json_build_object('success', false, 'error', 'Établissement non autorisé');
  END IF;

  -- Mark QR code as used
  UPDATE qr_codes 
  SET is_used = true 
  WHERE id = v_qr_code.id;

  -- Update booking status
  UPDATE bookings 
  SET 
    status = 'completed',
    validated_at = NOW(),
    updated_at = NOW()
  WHERE id = v_booking.id;

  -- Calculate amounts
  v_commission_amount := v_deal.discounted_price * v_business.commission_rate;
  v_salon_amount := v_deal.discounted_price - v_commission_amount;

  -- Update commission log
  UPDATE commission_logs 
  SET 
    status = 'paid',
    validated_at = NOW()
  WHERE booking_id = v_booking.id;

  -- Update business totals
  UPDATE businesses 
  SET 
    total_commission_owed = total_commission_owed + v_commission_amount,
    total_validated_bookings = total_validated_bookings + 1
  WHERE id = v_business.id;

  -- Award loyalty points to customer
  IF v_booking.user_id IS NOT NULL THEN
    UPDATE user_profiles 
    SET 
      loyalty_points = loyalty_points + v_loyalty_points,
      completed_bookings_count = completed_bookings_count + 1
    WHERE id = v_booking.user_id;
  END IF;

  -- Create validation record
  INSERT INTO booking_validations (
    booking_id, qr_code_id, business_id, validated_by, validated_at
  ) VALUES (
    v_booking.id, v_qr_code.id, v_business.id, p_staff_id, NOW()
  );

  -- Return success result
  v_result := json_build_object(
    'success', true,
    'booking_id', v_booking.id,
    'customer_name', v_booking.customer_name,
    'service_name', v_deal.title,
    'business_name', v_business.name,
    'deal_amount', v_deal.discounted_price,
    'commission_amount', v_commission_amount,
    'salon_amount', v_salon_amount,
    'commission_rate', v_business.commission_rate,
    'loyalty_points_earned', v_loyalty_points
  );

  RETURN v_result;
END;
$$;